### PR TITLE
improvements and cleanups

### PR DESCRIPTION
**Pull request by dek3rr**
Thank you so much for making this all work! I just wanted to offer some cleanups and make it easier for others to use.

-improved version checking for OpenSCAD
-use numpy definition of pi
-consolidate code used in maze file generation
-use "with" statement to handle file open/close
-better parsing of opt.txt so it can be modified and run directly with comments

### CODE REVIEW

**Comment by ex-nerd** [comment]
I should have checked for an existing PR before doing a bunch of similar work on my own.  I think I'll incorporate your ideas before submitting my larger set of changes (if nothing else, my choice to run everything through`black` to clean up the code means the diffs have diverged a bunch): https://github.com/ex-nerd/remix-of-Russian-Doll-Maze-Puzzle-Box

**Review by jmerc77 — CHANGES_REQUESTED** [review]
in main.py...

rd.seed(int(round(time.time() * 1000)))
on line 275 should occur before...
marr=genmaze(int(mw),int(mh),stag,st,ex)
on line 256 so that a more "random" maze is generated for the first maze.

**Comment by jmerc77** [comment]
White spacing in make_shells.scad could also use some work. Is there a good tool for that?

**Comment by ex-nerd** [comment]
@jmerc77 There's already a `rd.seed()` on line 253.  Honestly, there should only need to be one call into `rd.seed()` in the whole file -- resetting it risks ending up with *less* random.  The only reason I can think of to reset the seed is in a multithreaded environment where you want to make sure that the different threads each have their own random seed (looks like you had some earlier code that tried this?).  The alternative would be to use `os.urandom()` but that's probably overkill for this case.  You also don't need to provide any additional parameters to `rd.seed()` because it defaults to using the system time.

**Comment by jmerc77** [comment]
OK. in that case just have the seed once at the start and not in the loop.

**Comment by ex-nerd** [comment]
@jmerc77 yeah.  Give me a couple hours and I'll submit a PR that has my own fixes along with the ones from @dekerr.

**Review by jmerc77 — APPROVED** [review]

**Pull request closed without merging**
